fix checkstyle step in pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,22 +17,32 @@ jobs:
     - name: Install dependencies
       run: sudo apt-get update && sudo apt-get install -y g++ make cmake clang-format python3-pip
 
-    - name: Install cpplint
-      run: pip3 install cpplint
-
-    - name: Check code style with clang-format
+    - name: Check code style
       run: |
-        for file in $(find . -name '*.cpp' -o -name '*.hpp'); do
-          clang-format -style=file -output-replacements-xml $file | grep -c "<replacement " > /dev/null
-          if [ $? -ne 1 ]; then
+        function run_clang_format {
+          local file=$1
+          local result=$(clang-format -style=file -output-replacements-xml "$file")
+          local replacements=$(echo "$result" | grep -o "<replacement " | wc -l)
+          if [ "$replacements" -ne 0 ]; then
             echo "Code style issues found in file: $file"
-            exit 1
+            clang-format -style=file "$file" | diff "$file" - | colordiff
+            echo "Number of replacements: $replacements"
+            return 1
+          fi
+        }
+
+        echo "Running clang-format..."
+        clang_format_failed=0
+        for file in $(find . -name '*.cpp' -o -name '*.hpp'); do
+          if ! run_clang_format "$file"; then
+            clang_format_failed=1
           fi
         done
 
-    - name: Check code style with cpplint
-      run: |
-        cpplint $(find . -name '*.cpp' -o -name '*.hpp')
+        if [[ $clang_format_failed -ne 0 ]]; then
+          echo "clang-format check failed."
+          exit 1
+        fi
 
     - name: Build
       run: |
